version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: acme-postgres
    environment:
      POSTGRES_DB: acme_salary
      POSTGRES_USER: acme
      POSTGRES_PASSWORD: acme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
